name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout REST Framework
      uses: actions/checkout@v2
      with:
        repository: rest-for-physics/framework
        ref: master
        path: framework
      
    - name: Checkout this repository (Geant4Lib)
      uses: actions/checkout@v2
      with:
        path: framework/source/libraries

    - name: Debug
      run: |
        ls -lht ${{github.workspace}}/framework
        ls -lht ${{github.workspace}}/framework/source
        ls -lht ${{github.workspace}}/framework/source/libraries

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      
