name: Validation

on:
  workflow_dispatch:
  workflow_call:

env:
  CMAKE_BUILD_TYPE: Release
  REST_PATH: /rest/geant4lib/install
  G4_LIB_PATH: geant4lib
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:

  check-library:
    name: Validate library
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lobis/root-geant4-garfield:rest-for-physics
    steps:
      - uses: rest-for-physics/framework/.github/actions/checkout@master
        with:
          branch: ${{ env.BRANCH_NAME }}
          repository: rest-for-physics/geant4lib
          path: ${{ env.G4_LIB_PATH }}
      - run: python3 ${{ env.G4_LIB_PATH }}/pipeline/validateLibrary.py .

  precommit-config:
    name: Validate pre-commit config
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lobis/root-geant4-garfield:rest-for-physics
    steps:
      - name: Checkout geant4lib
        uses: rest-for-physics/framework/.github/actions/checkout@master
        with:
          branch: ${{ env.BRANCH_NAME }}
          repository: rest-for-physics/geant4lib
          path: ${{ env.G4_LIB_PATH }}
      - name: Verify pre-commit config files match
        run: |
          cd ${{ env.G4_LIB_PATH }}
          curl https://raw.githubusercontent.com/rest-for-physics/framework/master/scripts/validatePreCommitConfig.py | python

  build-geant4lib:
    name: Build only geant4lib
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lobis/root-geant4-garfield:rest-for-physics
    steps:
      - uses: actions/checkout@v3
      - name: Build and install
        uses: rest-for-physics/framework/.github/actions/build@master
        with:
          cmake-flags: "-DCMAKE_INSTALL_PREFIX=${{ env.REST_PATH }} -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} -DREST_WELCOME=ON -DRESTLIB_GEANT4=ON"
          branch: ${{ env.BRANCH_NAME }}
      - name: Load REST libraries
        run: |
          source ${{ env.REST_PATH }}/thisREST.sh
          restRoot -b -q
